# Generated by Django 4.2.2 on 2023-09-12 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_customuser_options_alter_customuser_managers_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Camion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camion', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('shift', models.CharField(max_length=255)),
                ('cluster', models.CharField(max_length=255)),
                ('destination', models.CharField(max_length=255)),
                ('capacité', models.FloatField()),
                ('quantité', models.FloatField()),
                ('date', models.DateField()),
                ('debut', models.TimeField()),
                ('fin', models.TimeField()),
            ],
        ),
    ]
