# Generated by Django 4.2.2 on 2023-09-12 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_camion'),
    ]

    operations = [
        migrations.AddField(
            model_name='camion',
            name='img',
            field=models.ImageField(blank=True, upload_to='camion_images/'),
        ),
    ]
