# Generated by Django 4.2.2 on 2023-09-15 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_camion_img'),
    ]

    operations = [
        migrations.RenameField(
            model_name='camion',
            old_name='capacité',
            new_name='capacity',
        ),
        migrations.RenameField(
            model_name='camion',
            old_name='quantité',
            new_name='quantity',
        ),
    ]
