# Generated by Django 4.2.2 on 2023-09-17 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_rename_capacité_camion_capacity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='img',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
