# Generated by Django 4.2.2 on 2023-09-17 12:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_alter_camion_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camion',
            name='img',
            field=models.ImageField(blank=True, upload_to='camion_images/'),
        ),
    ]
