# Generated by Django 4.2.2 on 2023-09-17 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_alter_camion_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='camion',
            name='img',
        ),
    ]
